version: 1.0.{build}

image: Visual Studio 2017

install:
  - ps: |
      if (!(Test-path -Path "C:\FFplay64")) {
        Write-Output "Download FFmpeg Dependencies"
        Invoke-WebRequest "https://drive.google.com/uc?export=download&confirm=eEoh&id=1vzQb965y_NldJlCxPwDmuGpAZ8Dt9OtT" -OutFile "C:\FFplay64.zip"
        Write-Output "Extract FFmpeg dependencies"
        Expand-Archive -LiteralPath C:\FFplay64.zip -DestinationPath C:\
      }
      $msbuild = (Get-Command msbuild).path
      Write-Output $msbuild

  - cmd: mvn --version
  - cmd: java -version


cache:
  - C:\apache-maven-3.5.4\
  - C:\Users\appveyor\.m2
  - C:\FFplay64\

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%\src\main\cpp
  - nuget restore MediaPlayer.sln
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - mvn -X -U -Pwin64-release -Dmaven.test.skip=true clean compile