version: 1.0.{build}

image: Visual Studio 2017

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem
          if (!(Test-Path -Path "C:\maven" )) {
            (new-object System.Net.WebClient).DownloadFile(
              'http://www.us.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip',
              'C:\maven-bin.zip'
            )
            [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
          }
          if (!(Test-path -Path "C:\FFplay64")) {
            (new-object System.Net.WebClient).DownloadFile(
              "https://drive.google.com/uc?export=download&id=1_7Dj88l-WIGq0mCe9LKIyBfHrzBz5ZIu"
            )
            [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\FFplay64.zip", "C:")
          } 
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: mvn --version
  - cmd: java -version
  - cmd: where msbuild

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
  - C:\FFplay64\

build_script:
  - mvn -Partifactory,win64-release -Dmaven.test.skip=true clean compile