language: java

jdk:
  - oraclejdk8

os:
  - windows
  - osx

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mvn -Pmac -Dmaven.test.skip=true clean compile;
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mvn -Pwin64-release -Dmaven.test.skip=true clean compile;